// src/lib/wordbanks.ts

type WordEntry = { word: string; length: number };

export const wordBanks: Record<string, WordEntry[]> = {
	animals: [
		{ word: "cat", length: 3 },
		{ word: "elephant", length: 8 },
		{ word: "lion", length: 4 },
		{ word: "hippopotamus", length: 12 },
		{ word: "dog", length: 3 },
		{ word: "tiger", length: 5 },
		{ word: "zebra", length: 5 },
		{ word: "giraffe", length: 7 },
		{ word: "bear", length: 4 },
		{ word: "monkey", length: 6 },
	],
	countries: [
		{ word: "canada", length: 6 },
		{ word: "brazil", length: 6 },
		{ word: "japan", length: 5 },
		{ word: "italy", length: 5 },
		{ word: "france", length: 6 },
		{ word: "spain", length: 5 },
		{ word: "germany", length: 7 },
		{ word: "india", length: 5 },
		{ word: "china", length: 5 },
		{ word: "egypt", length: 5 },
	],
	colors: [
		{ word: "red", length: 3 },
		{ word: "blue", length: 4 },
		{ word: "green", length: 5 },
		{ word: "yellow", length: 6 },
		{ word: "purple", length: 6 },
		{ word: "orange", length: 6 },
		{ word: "black", length: 5 },
		{ word: "white", length: 5 },
		{ word: "pink", length: 4 },
		{ word: "gray", length: 4 },
	],
	fruits: [
		{ word: "apple", length: 5 },
		{ word: "banana", length: 6 },
		{ word: "cherry", length: 6 },
		{ word: "grape", length: 5 },
		{ word: "lemon", length: 5 },
		{ word: "melon", length: 5 },
		{ word: "peach", length: 5 },
		{ word: "plum", length: 4 },
		{ word: "fig", length: 3 },
		{ word: "kiwi", length: 4 },
	],
	adjectives: [
		{ word: "happy", length: 5 },
		{ word: "sad", length: 3 },
		{ word: "fast", length: 4 },
		{ word: "slow", length: 4 },
		{ word: "big", length: 3 },
		{ word: "small", length: 5 },
		{ word: "bright", length: 6 },
		{ word: "dark", length: 4 },
		{ word: "loud", length: 4 },
		{ word: "quiet", length: 5 },
	],
	verbs: [
		{ word: "run", length: 3 },
		{ word: "jump", length: 4 },
		{ word: "walk", length: 4 },
		{ word: "think", length: 5 },
		{ word: "swim", length: 4 },
		{ word: "fly", length: 3 },
		{ word: "eat", length: 3 },
		{ word: "drink", length: 5 },
		{ word: "read", length: 4 },
		{ word: "write", length: 5 },
	],
	nouns: [
		{ word: "table", length: 5 },
		{ word: "chair", length: 5 },
		{ word: "book", length: 4 },
		{ word: "pen", length: 3 },
		{ word: "school", length: 6 },
		{ word: "car", length: 3 },
		{ word: "bus", length: 3 },
		{ word: "bottle", length: 6 },
		{ word: "phone", length: 5 },
		{ word: "computer", length: 8 },
	],
	emotions: [
		{ word: "joy", length: 3 },
		{ word: "anger", length: 5 },
		{ word: "fear", length: 4 },
		{ word: "love", length: 4 },
		{ word: "hate", length: 4 },
		{ word: "surprise", length: 8 },
		{ word: "trust", length: 5 },
		{ word: "disgust", length: 7 },
		{ word: "anticipation", length: 12 },
		{ word: "envy", length: 4 },
	],
};
